print("Task 0")
print("")
print("Robins will wear their feathery fire,")
print("Whistling their whims on a low fence-wire")
print("And not one will know of the war,")
print("not one...")
print("")
print("Task 1")
print(f"Hours in a week : {7 * 24}")
print(f"Minutes in a week : {7 * 60 * 24}")
print(f"Seconds in a week : {7 * 60 * 60 * 24} ")
print("")
print("Task 2")
name=input("What's your name?")
email=input("What's your email adress?")
nickname=input("What's your nickname?")
print("Your name= "+ name)
print("Your email= "+ email)
print("Your nickname "+ nickname)
print("")
print("Task 3")
name1=input("What's your name?")
victim=input("What's victims name?")
print("Thank you,"+ name1 +"!")
print("But our" + victim +"is in another castle!")
print("")
print("Task 4")
name2= "Courier"
age= 34
city= "New Vegas"
print(f"Hi {name2}, you are {age}. You live in {city}.")
print("")
print("Task 5")
name3= "Aki Hayakawa"
age2= 19
skill1 = "python"
level1 = "beginner"
skill2 = "2d art"
level2 = "beginner"
lower = 2000
upper = 3000
print(f"My name is {name3} and I'm {age2} years old.")
print("My skills are")
print(f"- {skill1} ({level1})")
print(f"- {skill2} ({level2})")
print(f"My salary expectation is {lower}-{upper} euros per month")
print("")
print("Task 6")
number1=6
number2=9
print(f"{number1}+{number2}={number1+number2}")
print(f"{number1}-{number2}={number1-number2}")
print(f"{number1}*{number2}={number1*number2}")
print(f"{number1}/{number2}={number1/number2}")
print("")
print("Task 7")
weight=float(input("What's your weight in kg?"))
height=float(input("What's your height in m?"))
print(f"Your BMI is {weight/(height*height)}")
print("")
print("Task 8")
videogame=input("Give me a videogame name:")
videogameage=input("When did it came out?")
print(f"{videogame} is {2025-int(videogameage)} years old.")
print("")
print("Task 9")
number3=int(input("Pls type in the first number: "))
number4=int(input("Pls type in the second number: "))
number5=int(input("Pls type in the third number: "))
product=number3*number4*number5
print("The product is ", product)
print("")
print("Task 10")
weekly_cafeteria_time=int(input("How many times a week do you eat at the student cafeteria?"))
lunch_price=int(input("The price of a typical student lunch?"))
grocery_price=int(input("How much money do you spend on groceries in a week?"))
print("")
print("Average food expenditure: ")
daily_lunch=float(weekly_cafeteria_time*lunch_price/7)
daily_grocery=float(grocery_price/7)
print(f"Daily: {daily_lunch+daily_grocery}")
print(f"Weekly: {(daily_lunch+daily_grocery)*7}")
print(f"Monthly: {(daily_lunch+daily_grocery)*30}")
print("")
print("Thx for checking :)")
print("")